version: "3"

services:
  hellohue:
    container_name: hellohue-dev
    build: .
    command: "npm run dev"
    volumes:
      - ./:/app
    ports:
      - "4568:4568"
    environment:
      - TZ=Europe/Paris